# Generated by Django 3.2.23 on 2023-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_full_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_phone_number',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='completed_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_section',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Applications', 'Applications'), ('Infrastructure and Networking', 'Infrastructure and Networking'), ('Database Administrator', 'Database Administrator'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
